// ─── NOCHES DE MAYA — STORY CONTENT ────────────────────────────────────────
// Noches de maya — Short story collection by Chico Montecristi
// Language: Spanish
// All stories complete. Chapters 1-2 free, 3+ gated by subscription.

import type { Chapter } from "@/lib/types";

export const NOCHES_CHAPTERS: Record<string, Chapter> = {
  "triste-de-cuna": {
    slug: "triste-de-cuna",
    bookSlug: "noches-de-maya",
    number: 1,
    romanNumeral: "UNO",
    title: "Triste de cuna",
    subtitle: "La noche, el viejo, la jaula",
    epigraph: {
      text: `—Viejo, ¿estás despierto?`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 1458,
    paragraphs: [
      { index: 0, text: `—Viejo, ¿estás despierto? —le preguntó en la oscuridad de la noche. No le contestaba por más que se prestó. Remeneándolo como cerezo japonés, logró abrirle los ojos, pero no decía nada. Había muerto hace varios días y ella no lo notaba, eso creo. —Viejo, me ha salido otra cana—exclamó, con ella en la mano. Alcanzó por encima de su espalda cuadrada, agarrándole su lánguido brazo y se la enseñó como muestra de que no mentía. —Mira, no te miento—continuaba. Eran las dos y media. Les acompañaba la calma del sereno, rosando las palmas contra el techo. Arañaban igual que las olas montecristeñas despidiéndose de la blanca arena. La puerta de aquella vieja letrina se oía golpear, suavemente, contra una cadena oxidada y el zumbido de un mosquito afeminado llenaba el silencio alarmante que les ahogaba, dentro del mosquitero. Sobre aquellas pálidas paredes de cuaba, bailaba la sombra de un lagarto rascando su garganta, cerca de la ventana. Por sus huecos y grietas, se colaban los cantos de sapos y chicharras que, dulcemente, dormían a la madrugada. Una sinfonía de caricias se sentía en la brisa, lubricándose con la tibia humedad dentro de los pétalos sangrientos de las cayenas. La huella de una babosa perdida, sobre las losetas cuarteadas del jardín desvanecía, a varias piedras de la orilla que por las noches secaba. Una perra tetona temblaba recostada detrás del anafe, sacudiéndose las garrapatas tras su oído. El negro gato insomnio, por su nariz pasaba cansado y guipaba de reojo, sin mucho de qué hablar, siquiera se lamía. Ambos escuchaban la puerta golpear la cadena y vigilaban cada pequeño fragmento que, más allá de las palmas, las olas traían. Dos neuróticos desvelados, incapaces de despertar. A su lado,` },
      { index: 1, text: `una jaula de cría: dos conejos ciegos, una gallina gira y un par de rasconcillos que no cesaban de arrullar. La gira dormía apoyándose de un palo atravesando la jaula descompuesta, llena de grisácea cica que no paraba de caer, pintando todo lo que le rodeaba, incluyendo la perra que, debajo de ella dormía. El jardín estaba lleno de latas de aceite crisol vestidas de jazmines, orquídeos y orejas de ratón. Allí habitaban unas mariquitas, gusanos verdes, grillos, arañitas y una cacata peluda con ojos de belluga. Se podían ver pequeñas hormigas marchando dentro del caparazón de una vieja tortuga cargando bolitas negras hacia un laberinto de pan. Los hábiles anteojos de cangrejitos merengueros, muy cerca bailaban, bajo la luna nueva. En la arena sumergían sus dedos, hacían burbujas y espumas blancas, aposadas en sus conchas. Se espantaban hasta con el eco que muy dentro sonaba. Aquí, cerca de la salada orilla, las palmas de coco campestre decoraban el paisaje con su tronco cenizo y arrugado. En la cima, su cabellera frondosa, exhibían un par de frutos a través de la luz menguante, que a la vez era brillo y a la vez era nada, talvez el reflejo de la luz sobre el espejo azul, o las luces cruzando cientos de kilómetros, de cayo a cayo. Un dulce sonido, de sus canas brotaba, como un ábaco rudimentario u la lluvia inconsciente desbordada sobre las hojas de cinc, un poco antes de anochecer. El cielo, sospechoso de traición, iluminaba con estrellas la oscuridad que le rodeaba, algunas fugaces quemaban desde su interior, emitiendo el último llanto hacia Nairobi, la cual, bajo poca luz, se desvelaba. Era de poco dormir, siempre encontraba una que otra cosa que hacer. Arreglaba el mosquitero, rellenaba la lámpara y limpiaba su cristal con periódicos del año anterior. Ataba sogas de distintos colores en forma de bandera y las convertía en hamacas para venderles a los turistas que visitaban al morro y sus cautivantes salinas.` },
      { index: 2, text: `No muy amante a la comida, algunas verduras, un pedazo de casabe y su taza de café por las mañanas y justo después de comer. Siempre tomaba agua de coco y comía de su blanca masa, dejando su greña caer por doquier, mientras que la dulce azúcar, en sus labios se asentaba. Las hormigas caribes, festejaban con regocijo y formaban un escándalo estrenuo cuando sentían el último bocado por su boca vibrar. Algunas greñas secas llevaban rostros de gente que, al parecer, eran hechos por un niño o una niña. Probablemente un niño, se parecían más a máscaras y garabatos que rostros y caras. Los habían decorados con caracoles y vestían algas de diadema —pensándolo bien, a lo mejor era una niña, o talvez ambos jugaban al juego de crear lo imaginario dentro de un mundo de corto fin— eran elevados con ramas caídas y palos a la deriva que con ella traía, el alta mar. Brazos y piernas injertos con palma fresca, trenzada entre nervios y agujeros. Vestían faldas y pétalos caídos de la brisa de un ayer. Los rostros se fijaban hacia el allá, hacia lo desconocido, hacia la línea superficial del cielo, hacia la luz que cambiaba de colores por la noche y durante el día. Eran siete, de cada uno. Siete con faldas y siete desnudos. Todos dándole frente a Apolo y su deslumbrante luz, con sus pies enterrados en los fríos escombros de la arena. Húmedos. Pudriéndose junto a las vainas que a su lado yacían, tristes y vacías. Se arrastraban rarezas difíciles de percibir, algunas cargaban con espinas sobre su caparazón, otras buscaban uno que habitar. Qué habrán hecho para perder las suyas y si no las perdieron, por qué habrán de dejarlas. Desnudas, enredaban sus extremidades sobre los cadáveres y huesos ambiguos que, en su arenoso camino, encontraban. Expandían sus antenas con óptima sensibilidad, y parecían sentir el más mínimo cismo en los precipicios sumergidos bajo la salada fluidez. Que oscura es nuestra vida bajo el sol, que cochina aquella de una cochinilla ingiriendo mierda en` },
      { index: 3, text: `su soledad, como Nairobi, quien, hasta el sol de hoy, comía sola, aunque la acompañaban los cadáveres de sus familiares. Le gustaba el lambí que pescaba entre los corales. Lo limpiaba con limón y así se lo comía, sentada junto a ellos que, en el reflejo de sus ojos, felices se veían. A veces se sentía triste al ver que nunca querían de comer, pero siempre intentaba. —Es fresco—solía decirles, mientras le echaba un gajo de limón verde. Hay dos tipos de limón: verde y amarillo. No hay azul, rojo ni canela, solo verde y amarillo. Se los compraba a una vieja chiflera que los vendía en los muelles. Era una fruta que se le hacía difícil de prender sobre la vieja cabra, donde muy poco vivía. —¿De dónde son los limones? —le preguntó. —Son de Santa María. De la finca del señor Rodríguez —le respondió, la primera vez que de ella compró—. Son muy buenos, mire, puro jugo. —Deme un saco —le contestó. Tenía una lancha pequeña, azul cielo, de madera, con un motor de bajo consumo. Lo cuidaba más que a sus propios dientes, lo mantenía limpio, engrasado y anillado. Dentro, un galón de gasolina. Lo amarraba de un tronco de coco con una soga larga, gruesa, sin color y con un pequeño cubo le sacaba el agua salada que se colaba con las olas. Lo halaba sobre la arena hasta que mostrara las lapas que sobre su casco se apegaban. Con firmeza, las arrancaba, una tras otra, con el puñal de su abuelo y se las tiraba a la tetona Lasy y al gato Mizu. Ya extrañaban el saborcito de su masa y sabían que casi era hora de la próxima vuelta. —Bueno si no me quieres responder —le decía, resignada—. Regreso pronto, cuida de Nicolás. Voy al muelle. Tomó una pequeña pausa para observarlos una vez más antes de partir. Se acercó a ellos y le dio un beso a cada uno.` },
      { index: 4, text: `—Adiós mi amor, te comportas bien. Escucha a tu padre —le dijo a Nicolás, mientras lo tocaba en la frente. Su pelo se quedaba inmóvil, descolorido, y su rostro parecía a la piel de culebra. Le pasó la mano por su mejilla, suavemente, para no despertarlo—. Y tú, ¿no te vas a despedir de mí? —le exclamó a Emilio—. Ya no me besas, ni siquiera respondes. Será como quieras. Entre su pecho cuscuteó una llave que guardaba en sus brasieles. Abrió el candado que permanecía encerrándolos entre cadenas y pestillos. Era un candado de los buenos, color bronce. De camino a su lancha la perra y el gato le perseguían entre sus piernas, maullando y llorisqueándole. Se le notaba el hambre hasta en la forma de pedir. La perra casi podía mover sus patas traseras y el gato usaba una de sus vidas para sobar su cara sobre su tobillo izquierdo. La hicieron tropezar pisoteando sus calizos remendados, alzó su pierna y pisó fuertemente sobre un caracol. —¡Ya, ya! Pronto vengo —les prometió. 5` },
    ],
  },

  "dos-pajaros": {
    slug: "dos-pajaros",
    bookSlug: "noches-de-maya",
    number: 2,
    romanNumeral: "DOS",
    title: "Dos pájaros",
    subtitle: "El nido, las dunas, la corona verde",
    epigraph: {
      text: `Como pájaro de cuatro dedos...`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 873,
    paragraphs: [
      { index: 0, text: `Como pájaro de cuatro dedos formo un nido de canas y hojas de palo verde. Dispongo de una rama llena de espinas lejos del polvo. Al pasar el cuerpo tibio de un lagarto escurridizo pongo la primera pieza que apoya lo demás. No pienso en la distancia del charco que seca, ni de la brisa fría que de noche cae sobre mi árbol, sólo la firmeza en el mecer de mi rama complace mi deseo amargo de poner una pluma más sobre su tronco. La sierra en el horizonte de picos en curva, piedras cuarteadas por el tiempo y la lluvia de agosto, algunas muestras de la muerte fijadas en huesos entizados, en los picos sedosos de buitres y en la suave piel endurecida de un alacrán.` },
      { index: 1, text: `Entre las nubes, aún más alto que la montaña, se posa un águila que al parecer era hombre y a la vez mujer, ambos en uno, volaba sin complejos ni tormentos, sin inquietudes ni desechos. Miraba hacia mi árbol y descifra el gusano que cargaba entre mis patas. Imagino que a ella le gusta algo que vuela, algo que salta, algo que respira en la madrugada cantando.` },
      { index: 2, text: `Fui padre varias veces, pero a todos los dejé, algunos se criaron en el bosque, otros cayeron muy pronto de su nido. Si los veo, lo admito, no los reconozco. Ya sus alas han cambiado de plumaje y no recuerdo el matiz de sus ojos ni aquella suave muda que hacían cuando aún eran polluelos.` },
      { index: 3, text: `El sonriente cascabel con su lengua limpia sus labios, probando el moco de las membranas vírgenes y olfateando las yemas amarillas que endulzaban los pequeños huesos huecos que se formaban bajo el caparazón del huevo. Hay un gozo que no comparto con mis hermanos, sólo yo sé lo dulce que es la carne de un huevo fecundado.` },
      { index: 4, text: `Qué triste fue ver que uno ya tenía sus alitas formadas, su pico era marrón, así lo recuerdo, y muy arriba los huecos dibujaban su nariz. Nunca podrá oler la fragancia de la lluvia que cae sobre la sierra, ni beberá del charco que a veces se llena con el agua de agosto, ni cantará en la madrugada como sus hermanos.` },
      { index: 5, text: `Te veo de la parte más alta, la corona verde, te veo cuscutear entre las pajas tus agujas, pero ya no están, para qué te lo digo. Mira más debajo y verás que sería mejor dejar aquello en el olvido. Aunque no lo creas, aún vuela la madre, buscando semillas y raicillas para llevar a los que se quedan dentro de los nidos.` },
    ],
  },

  "viejo-amigo": {
    slug: "viejo-amigo",
    bookSlug: "noches-de-maya",
    number: 3,
    romanNumeral: "TRES",
    title: "Viejo amigo",
    subtitle: "La distancia, el ron, la imaginación",
    epigraph: {
      text: `Qué pena saber...`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 3059,
    paragraphs: [
      { index: 0, text: `Qué pena saber que al otro lado vez algo inalcanzable, que por más que quieras sentir el latido entre tus dedos la vida te recuerda que no es cuándo tú quieras si no cuando sea. Organizamos el tiempo como si fuera materia. Nos echamos al bolsillo los minutos, las horas, los años, convencidos de que podremos doblegar el espacio en donde habita esta ilusión.` },
      { index: 1, text: `Digamos que Pablo es un hombre común y corriente: se graduó del colegio, fue a la universidad, se encontró a alguien que le dijo aquellas dos palabras más ponderosas que "vida" y "muerte", "te quiero", decidió formar un hogar, conseguir trabajo, vivir en una casa blanca, adoptó un perro, y en los últimos diez años ha visto desfilar su juventud en el espejo cada vez que se mira.` },
      { index: 2, text: `Imaginemos que Pablo ha aprendido a valorar las cosas que ha conseguido, que ha logrado adquirir con su esfuerzo, el perfecto balance de la sonrisa y el beso a su mujer, que puede levantarse y continuar un día más, que cada vez que acaricia su perro un pequeño sentimiento de calidez lo mantiene vivo. Una rutina. Una red de ilusiones que sostiene el cuerpo del deseo.` },
      { index: 3, text: `Después de caminar al perro, Pablo se da cuenta de que la última gota ha caído en el envase y que necesita avisarle a Carlota que "ya está el café" (il y a du café, como dicen los franceses) -se me olvidó decirles que Pablo y Carlota son de familia que viajan, que hablan varios idiomas, aunque viajan a las mismas playas y comen en los mismos restaurantes.` },
      { index: 4, text: `Estos segundos que pocos pueden explicar el por qué los nervios nos hacen sentir "a gusto", digamos, bueno sí se puede explicar, pero sabemos que pocos investigamos estas cosas, un poco absurdas comparadas con la vida, son estos los momentos en donde aquella sensación se apodera de todo lo que significa estar vivo, la respiración, el corazón, la lógica de los actos.` },
      { index: 5, text: `Aquí hago una pausa que me agobia… ¿Cuántos años son suficientes de vida? Después de ser consientes supongo, después del primer beso, el primer orgasmo, el primer rompimiento, el primer padre o abuelo que enterramos. Son estos los peldaños que caminamos hacia arriba, o hacia abajo, dependiendo de donde se encuentre la salida.` },
      { index: 6, text: `También me pasó que un día mi compañero de dormitorio me encontró "observando el crecimiento de mis cojones", esa fue mi escusa aquella vez, y sí se lo creyó. Espero que no lea esto, me sentiría muy avergonzado de que supiese que aún recuerdo aquel momento. Era verdad, pero no completamente, le confieso que también observaba la pared y descifra aquel espacio entre mi dedo pulgar y el índice, intentando calcular la diferencia.` },
      { index: 7, text: `En este caso, pues no me avergüenza, aunque ahora me avergüenza de alegrarme de la muerte de mi amigo, ya que me ahorraría la vergüenza de que lo leyera. Bueno, de todas formas, creo que (40), tal vez 30 años de vida, con sus penas y alegrías, son suficientes para sentir que ya viviste, que ya moriste, y que la realidad es apenas un sueño del que de rato en rato despiertas.` },
      { index: 8, text: `Vuelve a la carretera, con su perro atado, trotando a su lado, fiel amigo, en este caso debe ser un perro fuerte, lo cual me comprueba que elegir un pastor alemán o un dóberman fueron buenas razas para que pudiera tirar de aquella correa con fuerza, sin que el animal sintiese el tirón como algo negativo, como algo que rebaja su libertad, sino como una guía hacia el placer de la caminata.` },
      { index: 9, text: `Entonces, Pablo se pregunta, como siempre, ¿Por qué me siento tan vacío cuando tengo todo lo que siempre he querido? No lo dice en voz alta, no sean mal pensados, no se olviden que admitir este pensamiento sería cometer una traición, no sólo a Carlota, si no a la sociedad que ha invertido tanto dinero (tiempo) en que fuese feliz.` },
      { index: 10, text: `Les juro que no soy Pablo, si no me creen pues noten que el escritor, autor, como le quieran decir o llamar de aquí a que se lea, no se llama Pablo. Aunque si así hubiese sido, que me llamara Pablo, no lo admitiría a ustedes, ni siquiera a las personas más cercanas a mi corazón, así que descarten a Pablo como la persona que escribe esto.` },
      { index: 11, text: `Me da gracia, no lo de las "personas" que viven fuera de aquí en Tucson y como se nombren, si no de pensar que aún lees. Pero volvamos a Pablo para que no nos confundamos tanto, lo simple no se debe complicar, sobre todo en estas páginas donde todo debe ser claro, todo debe brillar como una verdad de Dios que sólo se cree si sale de la boca de otro.` },
      { index: 12, text: `Entonces, ¿Qué es en verdad lo que hace Pablo? Está combatiendo un pensamiento vergonzoso frente a un hombre que, al parecer, no tiene nada, pero que aún vive, mendiga por vivir, sobrevive a lo mejor porque la muerte ha tenido paciencia o porque Dios aún cree que hay esperanza en él, así que es mejor ponerlo como ejemplo de lo que él no quiere ser, un hombre vacío.` },
      { index: 13, text: `Para poder usarlo de ejemplo tenemos que acordar dos cosas: primero, se debe asumir que el mendigo es infeliz con su presente realidad, debemos mantener la objetividad al asumir al mendigo como ejemplo negativo, segundo, Pablo debe verlo, debe enfrentarse a la verdad que representa, de lo contrario, ¿cómo se suponía que iba a temer lo que no ve, lo que no entiende?` },
      { index: 14, text: `Tal vez no podemos darle un nombre de inmediato, pero sí podemos eliminar algunos nombres que no puede tener. El más obvio "Pablo" y el segundo, por motivos de sonido y falta de creatividad "Carlos". Pasemos hacia otro. Aunque la mayoría va a pensar que nombro a un fantasma, así que decidan si prefieren creerlo o no.` },
      { index: 15, text: `Para ahorrar aquel tiempo que puede ser perdido y que como hemos escuchado tantas veces, nunca parará de correr, nombrémosle "Carlos" a nuestro mendigo soldado contra su realidad, que ya se ha asumido como una sombra de sí mismo, vagabundeando entre los barrios, pidiendo dinero con aquella sonrisa que aparenta, pero que sólo es una contracción de músculos faciales acostumbrados a la humillación.` },
      { index: 16, text: `No fue una botella muy conocida, a lo mejor ron del barato, pero alguien ha de habérselo tomado y en este instante ese alguien fue Carlos. Así se le pasa él, mendigando centavos para poder comprarse la libertad, aunque sea por una noche, aunque sea por algunos minutos, buscando aquella sensación que le permita olvidar que es un hombre que, como muchos otros, ha perdido el derecho a sentir.` },
      { index: 17, text: `De todas formas, Carlos ya está harto de su realidad, no la acepta por más que quiera o le recuerde el día a día, aquel que Carlota le llama "buen día". Se pierde en una botella y comienza a imaginarse a sí mismo como un hombre rico, como un hombre que pudo, que tuvo, que fue, que algo hizo con su vida que valía la pena contar.` },
      { index: 18, text: `Sentirse vacío dentro de un carro, siendo él mismo el objeto que satisface un espacio, no es igual que existir en la realidad vacía tratando de penetrar en un espacio inalcanzable, la conciencia, la ilusión, la fantasía de que algún día todo va a cambiar, aunque sabemos que la realidad no tiene memoria, que no sabe de promesas y que la distancia que nos separa de lo que queremos, casi siempre, es la misma.` },
      { index: 19, text: `Que inútil pensar que pude lograr entenderlo mejor, ya que vuelvo al mismo pensamiento que nunca tuve como enfoque. Mi viejo amigo… ¿Qué será de él de aquí hacia aquel momento? Después de todo lo dicho, todo lo vivido, todo lo imaginado, ¿cuántas botellas más habrán de pasar por sus labios antes de que la muerte lo tome de la mano?` },
    ],
  },

  "pinto-un-largo-cristal": {
    slug: "pinto-un-largo-cristal",
    bookSlug: "noches-de-maya",
    number: 4,
    romanNumeral: "CUATRO",
    title: "Pinto un largo cristal",
    subtitle: "Nuevo México, la biblioteca, los lagartos",
    epigraph: {
      text: `El camino no daba pérdidas...`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 1135,
    paragraphs: [
      { index: 0, text: `Hoy tuve que buscar una pieza olvidada en un pequeño motel a orillas de Nuevo México. El camino no daba pérdidas, todo recto y al final una derecha. Al pasar la hora los carros comenzaban a reducir velocidad, la carretera se iba haciendo un poco más oscura con la sombra de los montes. Había poca gente y el sol estaba bajando.` },
      { index: 1, text: `Por poco paso la parada, era mi primera visita. Las luces encendidas decoradas con vidrios azul marino, en forma de reptil. El portón estaba abierto y en el garaje un carro. Había gente, pensé.` },
      { index: 2, text: `Camino a la oficina se escuchaban las voces de mucha gente, pero descubrí que era el ruido de un televisor. Toqué varias veces el timbre, pero nadie contestó. Volví a tocar, nada, siquiera un ruido. Dejé mis datos en una nota pegada en la puerta.` },
      { index: 3, text: `Me senté, esperé la llegada de otro huésped o la señora que me iba a recibir. Pasó la hora y por más que quise posarme bajo una sombra, ya no aguantaba el sol. Me paré a mirar hacia adentro con mis manos haciendo sombra en el espejo de la puerta de cristal.` },
      { index: 4, text: `No sé por qué, pero no me encontré extraño el televisor prendido, que nadie estuviera en el motel, que el eco del timbre se hundía en las paredes sin respuesta, que aquí, en medio del desierto, sólo pudiera escuchar el viento y mis propios pasos.` },
      { index: 5, text: `Me imaginaba que a lo mejor alguien me lograba ver, pero por miedo no abrieron, por temor se mantuvieron en silencio. Al fin, ¿quién era yo? Un desconocido viendo por las ventanas, un desconocido tocando timbres, un desconocido dejando mensajes incompletos.` },
      { index: 6, text: `Al final dejé mi información, un contacto, la hora, fecha exacta que lo escribí. Hasta en castellano, por si acaso. Volví a la carretera y busqué cosas que hacer mientras esperaba aquella llamada. Tiempo. Siempre el tiempo.` },
      { index: 7, text: `-Buenas tardes, habla…` },
      { index: 8, text: `-Sí, buenas tardes, soy yo la muchacha del motel. Disculpe no haberle contestado antes.` },
      { index: 9, text: `-No se preocupe señorita Lurdes, ¿cierto?` },
      { index: 10, text: `-Bueno, yo sólo quería buscar el suéter del cuarto del fondo, el que está más cerca de la piscina.` },
      { index: 11, text: `-Sí, aquí se lo tengo. ¿Puede pasar ahora?` },
      { index: 12, text: `Pensé en acordar para la próxima mañana, pero me acordé de lo inútil que fue gastar esa hora escuchando la misma noticia, sentado contra aquella pared.` },
      { index: 13, text: `-Por supuesto que puedo. Me tardaría algunos veinte minutos. ¿Qué le parece?` },
      { index: 14, text: `-Aquí estaré esperándolo- me dijo y colgó.` },
      { index: 15, text: `No me tardó tanto esta vez. Ya el sol se escondía detrás de la sierra, dejando una capa roja y negra sobre las nubes. Al doblar en la Pinto encendí los focos y lentamente me dirigí cuesta arriba. Dejé mi tarjeta debajo del limpiaparabrisas.` },
      { index: 16, text: `Toqué el timbre, dos pasos hacia atrás y fijé en mi rostro una sonrisa. Pero igual que esta mañana, nadie contestó. Volví a sentir aquella inútil emoción de esperar por algo. Llamé a Lurdes y pronto me contestó.` },
      { index: 17, text: `Después de varios timbres entró la máquina.` },
      { index: 18, text: `-Disculpe, en estos momentos no estamos disponibles. Favor de dejar su nombre y un número en donde podamos alcanzarlo.` },
      { index: 19, text: `Casi perdí la razón, pero con una pausa y un tragar de saliva -tanta sed tenía- comencé a grabar mi mensaje.` },
      { index: 20, text: `-Hola, soy yo. El muchacho del abrigo-. Paré de hablar al escuchar mi voz. Continué-. Volví al motel para encontrarme con usted, como lo habíamos acordado hace una hora. Por favor, señorita Lurdes, llámeme.` },
      { index: 21, text: `Me acordé que ya tenía mis datos y colgué. Regresé al carro y al sentarme recibí una llamada.` },
      { index: 22, text: `-Sí señor, la misma. ¿No va venir?` },
      { index: 23, text: `Salí del carro de prisa, corrí hacia la puerta, me olvidé de las noticias y fijé mi mirada hacia el teléfono, pero nadie. Sólo el reflejo de mi cuerpo a lo largo de aquel largo cristal.` },
      { index: 24, text: `- ¿Dónde está usted? Le pregunté. No la veo.` },
      { index: 25, text: `-Estoy al otro lado del monte.` },
    ],
  },

  "a-espaldas-de-mi-abuela": {
    slug: "a-espaldas-de-mi-abuela",
    bookSlug: "noches-de-maya",
    number: 5,
    romanNumeral: "CINCO",
    title: "A espaldas de mi abuela",
    subtitle: "La dulzura, el hábito, la cama",
    epigraph: {
      text: `Mi abuela era muy dulce.`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 755,
    paragraphs: [
      { index: 0, text: `Mi abuela era muy dulce. Por las tardes me cantaba canciones, en las mañanas desayuno y hasta el día de hoy creo que me quiso más que a su propio hijo. Confieso que por más que me dijo te quiero nunca lo creí, aun en estos momentos en donde ya no está, cada noche trato de recuperar aquellas palabras que guardé en la mano cerrada.` },
      { index: 1, text: `Recuerdo que una vez me compró mi primera corbata, negra, para ir a la iglesia, esto le trajo tanta alegría. A lo mejor lo veía como un nuevo comienzo, su segunda oportunidad de vida. Siempre planchaba mis camisas y ponía una corbata sobre la cama como si fuera lo más importante, como si mi corbata representara algo que yo no entendía.` },
      { index: 2, text: `Los fines de semana visitábamos a su hermana, la cual yo le decía tía. Por su patio corría un charquito cubierto de flamboyanes, nín, aguacate y mango. Un paraíso. Allí me pasaba las tardes estudiando bajo la sombra de un árbol muy viejo, ella me vigilaba desde la cocina.` },
      { index: 3, text: `-Te acuerdas de doña Juanita, ¿verdad?` },
      { index: 4, text: `Sí, le contestaba, aunque no tenía la menor idea. Todo por complacerla, es que era tan dulce conmigo y no tenía forma de mirarle los ojos y decirle que no. Una curiosidad que nunca me gustó, fue que, desde que tengo memoria, nunca vi llorar a mi abuela. Ni siquiera en el funeral de mi abuelo.` },
      { index: 5, text: `Fue tanto que me pregunté esto –sabiendo la mala persona que soy, lo oscura y dañina que es mi mente, el asco que siento al verme en el espejo, lo inútil que me siento aun siendo querido, la falta de compasión que cargo hacia mi propio ser- que si aquella dulzura que sentía por mí era verdadera o si era apenas un disfraz, una herramienta que usaba para mantenerme alejado de los peligros del mundo.` },
      { index: 6, text: `Tomé un vuelo a las seis con escala en el Kennedy. Tuvimos un retraso de una hora, algo que ver con el sobrepeso de las maletas. Anunciaron pasajeros tardíos, del tiempo que les queda para abordar ante la puerta de la terminal y cosas de este tipo. Aterricé de noche, alquilé un carro y manejé sin pensar en nada, sólo en lo que le iba a preguntar cuando la viera.` },
      { index: 7, text: `Fue una sorpresa mi llegada, pero fui bien recibido. En cuestiones de minutos me preparó un manjar de carnes, vegetales y aperitivos. Hasta hizo arepas con aquel viejo guayo que guindaba tras la puerta de la cocina, el que no sabía que existía. Con una sonrisa en su rostro me sirvió todo sobre la mesa, sin dejarme ayudar en nada.` },
      { index: 8, text: `Desperté sin sentir el aroma de su café tostado, sin escuchar el dulce canto de su voz en harmonía, sin ver las hebras de su pelo en aquel viejo peine azul, sin escuchar su bendición y buenos días. Camino a la cocina noté que sus manos temblaban mientras escribía una nota. Me acerqué en silencio. Pero no alcancé a leerla, ella la rompió en pequeños pedazos que echó al aire.` },
    ],
  },

  "cuento-amarillo": {
    slug: "cuento-amarillo",
    bookSlug: "noches-de-maya",
    number: 6,
    romanNumeral: "SEIS",
    title: "Cuento amarillo",
    subtitle: "La hija, la cuna, la mecedora",
    epigraph: {
      text: `Una noche de esas...`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 891,
    paragraphs: [
      { index: 0, text: `Una noche de esas que te encuentres abrazado de tu hija, que la beses y la abraces, le tiendas la cobija y le digas buenas noches, te quiero mucho mi niña… te llegará una pregunta complicada: "¿Me puedes contar la historia de mi hermano?"` },
      { index: 1, text: `Érase una vez, llevé a tu madre a una clínica de abortos. Habíamos decidido llamarle Julio como tu abuelo. Su cuarto estaba decorado con fotos de fútbol, coyotes y guitarras. Acuerdo que lo pintamos de amarillo, un amarillo muy vivo, el que aún recuerdo en las paredes.` },
      { index: 2, text: `El closet estaba lleno de calcetines, pañales, bobos, pañuelos, zapatillas de charol, una mochila con Topo Gigio y tantas, pero tantas sábanas que hasta hoy día no termino de contar. Su fecha de nacimiento estaba marcada en el calendario con un marcador rojo que tu mamá compró especialmente para eso.` },
      { index: 3, text: `En verdad no sé cómo explicártelo mi niña… Cuando regresaba de la faena me podía pasar horas sobándole su pansa, le cantaba canciones y escuchaba su latir poniéndole cerca mi oído –ven, pon tu oído sobre su pancita, está latiendo, es tu hermano- le decía. Ella sonreía con esa sonrisa que aún conserva.` },
      { index: 4, text: `A los seis meses me comenzó a hablar de la cortina. No le parecía que el color iba bien con el resto de la habitación.` },
      { index: 5, text: `- ¿Azul con amarillo?, se preguntaba.` },
      { index: 6, text: `Le ofrecí volver a pintar el cuarto, algo que se asemejara más.` },
      { index: 7, text: `- ¿No crees que afectaría el embarazo el olor a pintura?` },
      { index: 8, text: `Le respondí que era cierto y que sería buena idea que se fuera a la casa de sus viejos por el resto del mes, mientras pintara y se fuera el mal olor. - ¿A Montecristi, con ese calor? No le pareció buena idea aquella mañana, se lo vi en sus ojos.` },
      { index: 9, text: `-Nos vemos pronto mi reina, le dije.` },
      { index: 10, text: `-Asegúrate de que la cortina se incorpore con la pared.` },
      { index: 11, text: `-De acuerdo. Me dio un beso, besé su pansa y un adiós.` },
      { index: 12, text: `Hice todo exactamente como me lo había pedido. Reorganicé la ropa, puse la cuna y la mecedora en su lugar y volví a poner cada pañal y pañuelo justamente cerca a los calcetines. Ya mediado de junio regresó. Era una noche cálida, me recuerdo perfectamente.` },
      { index: 13, text: `No me lo dijo de una vez, pero sabía que no le agradó mi trabajo, no estaba complacida. Una noche despertó, aunque creo que nunca cerró los ojos, y me dijo:` },
      { index: 14, text: `-Esa maldita cortina… ¿Por qué tuvo que elegir ese color? No comprendo, sabe lo mucho que odio ese color. Hasta se lo advertí a todos antes del Babyshower. Ahora hay que tener esa estúpida cortina guindando toda la vida aquí.` },
      { index: 15, text: `-Amor, ¿por qué no le decimos que se manchó con alguna grasa o con la misma pintura y que por eso la tuvimos que quitar?` },
      { index: 16, text: `-Sabes que no me gustan las mentiras y mi familia no pararía de hablar, me respondió.` },
      { index: 17, text: `-Entonces, ¿qué hacemos? Es solamente un color. Con tal, ni siquiera estamos usando la habitación aún.` },
      { index: 18, text: `-Parece que no conoces a mi hermana…` },
      { index: 19, text: `- ¿Qué quieres hacer entonces?, le repetí. Pero ya estaba dormida.` },
    ],
  },

  "la-hermana-del-patron": {
    slug: "la-hermana-del-patron",
    bookSlug: "noches-de-maya",
    number: 7,
    romanNumeral: "SIETE",
    title: "La hermana del patrón",
    subtitle: "El secreto, el calor, el cartón",
    epigraph: {
      text: `Paco no le ha dicho a muchos...`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 1048,
    paragraphs: [
      { index: 0, text: `Paco no le ha dicho a muchos que su padre lo violó, ese secreto lo mantienen entre él y su mamá. Claro su papá también lo sabe, aunque a veces actúa como si no. Al principio su mamá lo tomó como una calumnia, a lo mejor había escuchado esa palabra en alguna telenovela y decidió usarla.` },
      { index: 1, text: `Darío, como se llamaba el padre y esposo, le dijo que se dejara de tonterías que todo estaba en su mente y que aún estaba tan guapa como aquella noche que la hizo su mujer. Lo cuál le trajo tanta gracia a la doña y, sin duda alguna, placer que fue al closet a buscarse unos aretes y fue directo a la cama.` },
      { index: 2, text: `Por la manera en que se lo cargaba se puede decir que entre las sábanas, aquella pasión, quemaba, hasta lo complació con una de esa fantasías suyas, pero mejor ni hablar de eso fue un poco asqueroso presenciarlo aunque sólo pude ver por el pequeño agujero de la tabla que está entre el piso de la cocina y donde yo dormía.` },
      { index: 3, text: `Durmieron como puros perros, así sucios y sudados, me imagino que debían de andar todo pegajosos, más ahora en pleno junio con tan poca lluvia, tanta humedad que sopla de las charcas de camino alJobo. A quién le miento, si fuera él al igual lo hubiera hecho, solo que yo no tengo una casa con una cama y sábanas de lino, esas que el patrón compró en la ciudad.` },
      { index: 4, text: `No sé como no se han dado cuenta todavía, hay veces que hasta yo mismo me asusto cuando se me encalambran las rodillas, a lo mejor es porque esta pared está pintada de amarillo y después que seca, pues, se pueden confundir. Dudo que se paren a ver de noche, menos el patrón que está acostumbrado a vivir en la ignorancia.` },
      { index: 5, text: `Eso fue lo que se me había olvidado, darle la pastilla a la llegua, dice el patrón que carga con uno, aunque no me parece, por algo lo habrá de decir, sólo soy un simple campesino. Creo que a estas horas ya es muy tarde, causaría graves ruidos y, aunque nadie en la casa va a escuchar, debo hacerlo de todas formas porque así es la vida, uno aprende a guardar los secretos de los patrones.` },
      { index: 6, text: `Hasta me está dando sed, de seguida me doy un baño ahí mismo que todavía queda jabón de cuaba que me rergaló el patrón, algo que ver con el olor a bestia que traía, aunque aún no noto de lo que me hablaba aquel día, pero es el patrón y dejé que me la regalara.` },
      { index: 7, text: `Y ni hablar de mi vieja-esa sí que lo respeta. La conoce desde pequeña, si aquí mismo nació. Una vez me contó que de pequeños cavalgaban, él se la echaba detrás en su caballo, pues apenas era una niña, poco sabía montar, y él ya casi un hombre, un muchacho, casi un hombre. Qué pena debe de tener ahora, pero como siempre, ha de cargar con su silencio.` },
      { index: 8, text: `Pero ni hablar de su hermana, esa sí que era una ramera.` },
    ],
  },

  "pies-secos-pies-mojados": {
    slug: "pies-secos-pies-mojados",
    bookSlug: "noches-de-maya",
    number: 8,
    romanNumeral: "OCHO",
    title: "Pies secos, pies mojados",
    subtitle: "Emilio, la botella, la ventana",
    epigraph: {
      text: `¿A dónde va Emilio?`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 892,
    paragraphs: [
      { index: 0, text: `¿A dónde va Emilio con tanta prisa? Le preguntó un viejo a su compañero de domino. Fumaba un puro y se mojaba los labios con un dedo de caña. No era muy calvo pero el pelo se le estaba adormeciendo. Sin dejar de jugar, su vecino le respondió: -No sé, pero desde que llegó la muchacha cada tarde desaparece.` },
      { index: 1, text: `Odiaba perder, mucho más contra su vecino que nunca paraba de hablar desde aquel día que le ganó por primera vez. De cierta manera era un masoquista, el vecino, todos le ganaban y hasta su mujer se la ganaba en las tardes cuando ella llegaba del trabajo.` },
      { index: 2, text: `Todos sabían que era buena mujer, de eso no había dudas. Me parece que una vez le vi pasándole unos pesos por debajo de la mesa a uno de los amigos, algo que ver con el aumento del peaje o del combustible. Ella no decía nada, sólo sonreía.` },
      { index: 3, text: `La muchacha era toda una salvaje, a veces los muchachos llegaban acompañados de primos hermanos, supuestamente necesitaban parejas. Ellos también jugaban domino. Por allá en los salados se usaba mucho jugar por dinero, aunque luego había que pagarse el viaje completo en guagua para poder llegar a la casa.` },
      { index: 4, text: `Siempre le dejaba su comida preparada en casa con ensalada de aguacate, hojas verdes, vinagre y limón. Le traía un café cargado, sin azúcar, una galleta de agua y una menta para aliviar su garganta milagrosamente inflamada.` },
      { index: 5, text: `El olor era rico, como una yunta de miosotis y encarnaciones justo antes del ocaso. Puede ser la colonia que usaba, la de Calvin Klein, la eternity. Por el barrio todos la compraban, pero eran falsificadas, claro, las traían de afuera en las maletas.` },
      { index: 6, text: `Primero, desdoblaba el plástico cuidadosamente, tienden a romper con muy poca presión. Luego, con sus uñas, levantaba las esquinas de la caja para luego levantar el pequeño papel blanco que cubría la parte inferior, donde vivía el verdadero placer.` },
      { index: 7, text: `En la mesa todos usaban el eternity y de cierta manera se bañaban en él, pero cuando se sentaba el vecino todos cerraban los ojos por un segundo y se embriagaban de esta penetrante fragancia de jardín, una que te lleva a pensar que la vida tenía algún sentido.` },
    ],
  },

  "mueren-dos": {
    slug: "mueren-dos",
    bookSlug: "noches-de-maya",
    number: 9,
    romanNumeral: "NUEVE",
    title: "Mueren dos",
    subtitle: "La sala, el taladro, el café",
    epigraph: {
      text: `Lo que pasa en los edificios viejos.`,
      attribution: "Noches de maya",
    },
    isLocked: false,
    wordCount: 17411,
    paragraphs: [
      { index: 0, text: `Content available to subscribers.` },
    ],
  }
};

export function getNochesChapter(slug: string): Chapter | null {
  return NOCHES_CHAPTERS[slug] ?? null;
}

export function getAllNochesSlugs(): string[] {
  return Object.keys(NOCHES_CHAPTERS);
}
