// ─── RECOLETA — CHAPTER CONTENT ─────────────────────────────────────────────
// Recoleta — A Novella by Chico Montecristi
// Language: Spanish
// Chapter Uno is free. Chapters Dos through Cuatro are sealed.

import type { Chapter } from "@/lib/types";

export const RECOLETA_CHAPTERS: Record<string, Chapter> = {
  "capitulo-uno": {
    slug: "capitulo-uno",
    bookSlug: "recoleta",
    number: 1,
    romanNumeral: "UNO",
    title: "Capítulo Uno",
    subtitle: "El Bronx, el invierno, el tío Vásquez",
    epigraph: {
      text: "Duermo por no querer estar despierto.",
      attribution: "Recoleta",
    },
    isLocked: false,
    wordCount: 4387,
    paragraphs: [
      { index: 0, text: `Duermo por no querer estar despierto, porque he creado un mundo a mi manera con mucho esfuerzo y sueño, duermo hasta poder lograr jamás despertar. No me agrada pensar que todo comenzó en aquel sótano mientras madre brindaba y bailaba al son de punta y bachata. El armario de la sala—mi dormitorio—yacía justamente al lado de las bocinas, al igual que el reclinatorio de mi tío, cual se pasaba de noche al alba gritando barbaridades y juzgamientos en forma de oratorio. Fue un importante político montecristeño en los tiempos más reverentes dentro del partido de los blancos; se había acostumbrado a los discursos, a la retórica social. Sociedad que, para él, sufría de cortedad.` },
      { index: 1, text: `Sufría de diabetes, mi tío Vásquez. La última vez que escuché sobre él fue cuando le amputaron la pierna restante, la comadreja. Por colmo, la primera imagen que se me vino a la mente al escuchar esta noticia fue la negra escalera de piedra maciza que daba paso al afuera, a la superficie, al piso encima de los escombros. Me imaginé las grietas de cada escalón, la falsa contrahuella y la escarcha oscura formándose sobre cada nariz—pensé en su piel fofa golpeando el tramo al resbalar y en las muletas cruzadas al pie de la puerta.` },
      { index: 2, text: `Aun cuando ya poco hacía, Vásquez, encontraba formas de mantener su virilidad invitando a compatriotas para discutir sucesos entre copas de whiskey y botellas de cerveza helada, halando a mujeres a su asiento, haciéndolas bailar contra la comadreja, y hasta daba unos pasos en la avenida Fulton, asegurándose de disimular su cojera. Nunca le vi fumar, aborrecía los cigarrillos y el fuerte olor a mota que permanecía en los pasillos del edificio—el dueño era un judío, al igual que el resto de los edificios en aquella corta avenida.` },
      { index: 3, text: `Tío todo lo hacía mientras fue encargado del mantenimiento de los cinco edificios, cada uno de cinco niveles y cuarenta apartamentos, exportador de motores refrigerios, representante político del comité de los blancos en el condado del Bronx, obrero de losetas, carpintero, albañil y, más que todo, promotor de fiestas. El don lo sabía y hacía todo, un nato handyman como se nos ha acostumbrado a decir. Un handyman que se estaba quedando sin dedos, vale la pena notar. Mientras más dedos le amputaban más se emborrachaba, rodeado de queridos compatriotas segunderos, las dulces salvadoreñas y una taza de leche, para aquello de la diabetes. Nunca me molestó su alcoholismo y con el tiempo me pude adaptar a las largas noches de baile y música, pero lo que nunca soporté fue su capricho de sacarme de mi dormitorio para verme bailar con una de las borrachas o de tomarse un trago de whiskey conmigo. Me enfadaba y él lo sabía. Se reía al ver mi timidez, mis brazos cruzados tras mi suéter de lana gris.` },
      { index: 4, text: `Las plantas de mis calcetines se mojaban casi inmediatamente al pisar las huellas de aguanieve y sal sobre las losetas blancas. Con el dedo índice formando un ademán semejante a un remolino, Vásquez, le señalaba a una de las muchachas para que me acompañara a bailar un merengue y a veces bachatas. Las caderas siempre paralelas a mi frente, besos de labio a labio. Con todas sus incógnitas, no sé a qué se debía el tanto respeto que le tenía a mi tío, en todo caso no era mi tío. Vásquez fue el padrastro de madre hasta que su madre, mi abuela, su esposa, falleció. Y al divorciarse madre del americano que nos trajo a estados unidos después de pasar aproximadamente cinco años casada con él—tiempo sugerido por abogados cuando se quiere obtener documentos americanos, legalmente—nos vimos obligados a buscar dónde vivir.` },
      { index: 5, text: `Antes de mudarnos, ya sabíamos algunas reglas: prohibido fumar, cada quién limpia lo suyo y las estampillas de comida deben de pasar por una inspección introductoria antes de ingresar al sótano. Como el agua… lo que aún no teníamos claro era ¿cómo llamarle? Tío Vásquez, la decisión.` },
      { index: 6, text: `La primera vez que fijé mi vista hacia abajo, hacia la puerta en los escombros rodeada de botellas rotas, gatos y ratones fue al oír el gruñido estremecedor surgiendo de la garganta y el pecho del, ya antes asignado, tío Vásquez mientras se desperezaba. Desde lejos pude notar sus ásperas manos, forjadas con una mezcla de carbón, cemento, hierro y yeso. Se perdían en las paredes de ladrillo, en sus líneas abrasivas, en la luz del sol de invierno justo antes del ocaso, en las rupturas de sus uñas semejante a las ventanas, en la negritud de las palmas resemblando a aquellos que, contra la pared, se recostaban. Dio el último paso—prefiero muletazo—hacia afuera, intercambiamos saludos entre abrazos y besos: natalicio de un tío en una tarde fría, en la corta avenida Fulton, Bronx, Nueva York.` },
      { index: 7, text: `Comenzó con lo cotidiano. Aquel ¿te acuerdas de mí? y el ¿sabes que te cargaba cuando apenas habías nacido? Preguntas que, en mí parecer, son retóricas y respuestas, en general, me faltaban. ¿A quién no? Pero hice lo que hubiese hecho en cualquier situación, de haberme sentido extraño—sonreí. Ya había mudado todos mis dientes para aquel entonces; sonreí con orgullo, con todo y diastema. A mi madre nunca le ha gustado, piensa que ha sido un descuido propio mientras apenas fui un niño, algo de meterme la lengua donde no debía. Me lo repite cada vez que nos vemos, ¿será que piensa que algo va a cambiar?, ¿que habrá un repentino cambio en mi diastema en el transcurso del declive de mi cuerpo?` },
      { index: 8, text: `Por suerte, cuando no estaba ebrio, mi nuevo tío hablaba poco, aunque si estudiaba mis ademanes, mi habilidad de ser autosuficiente, si podía depender de mí bajo su mando y hasta llegó a cuestionar mi desenvolvimiento académico cuando asistía a escuelas en Castañuelas. Al segundo día, acompañado por madre, me había inscrito en la escuela secundaria asignada a mi sector, Bronx del sur. Adiós uniforme, pensé. El inglés ya lo hablaba, pero después de vivir varios años en la República Dominicana se me hacía difícil utilizar otra que mi lengua natal. Joder, ¿qué iba yo a hacer? Me parecía una gran inconveniencia.` },
      { index: 9, text: `La escuela se concentraba en la ingeniería eléctrica, carpintería y formación de obreros, entre otras cosas. No era la mejor de escuelas, lo esperado se puede decir, pero me conformaba mucho el desayuno de huevos revueltos, cereal y leche que nos ofrecían en la cafetería. Las pequeñas cajitas de leche vestían vaquitas de distintos colores: rojo, verde, chocolate—mi favorita—y azul. Antes de entrar a la misteriosa, cuadrada estructura, envuelta en alambres de púa y fondos de botella que llamábamos escuela, parecíamos pingüinos agrupados, esperando que seguridad abriera a las 06:30. Nos empujábamos hacia las dos pequeñas puertas marrones en forma de embudo, nos embudaban como el rebaño de José—aquel fiel creedor de los milagros—o como los trecientos novillos al matadero antes o después del diluvio.` },
      { index: 10, text: `Ya embudados, formábamos filas frente al detector de metal, introducíamos nuestras mochilas, abrigos y zapatos. Para mis artículos, la luz siempre señalaba verde, mientras que a otros estudiantes le pedían esperar en la oficina del director, luego de que la luz señalara un color rojo vivo—que sencillo es cambiar el sentido de una cosa con sólo añadirle vida. Estudiantes, algunos pandilleros, cargaban armas blancas en ánimo de protección, de defensa propia decían. Nunca se me ocurrió hacerlo, ir a la escuela envainado; por más inseguro que me sintiera caminando entre barrios ajenos, por más pequeño que fuese la cuchilla o el puñal, mi única seguridad se encontraba en los salones de clases cerca al maestro, en el asiento del autobús que tomaba de lunes a viernes, en la misma parada y a la misma hora, asegurándome de no pisar la línea blanca. Mi seguridad se encontraba en aquel armario bajo miles de ladrillos y escaleras, en aquel cajón rodeado de fotos alumbradas por un pequeño bombillo que prendía al apretarlo, bajo aquella colcha que el alrededor desvanecía, tras aquella persiana de madera—la puerta—por donde aún se colaba la luz del televisor.` },
      { index: 11, text: `Vásquez veía los mismos programas a la misma hora, sin interrupción. Los transmitía por medio de una "caja negra" preprogramada con sesentaisiete canales, en los cuales HBO, Cinemax, Playboy y Spice no faltaban. Aún recuerdo los códigos que debíamos ingresar en caso de que se desprogramara, no sé por qué. Spice era mi canal favorito, especialmente la programación entre las 02:00 y 03:00—Softcore. No creo que exista el canal ya, a lo mejor es parte de algún conglomerado: Masturbation Channel. En fin, ese es el sentido de estos canales, masturbarse, y en vez de usar logos con caritas de conejitos sería mejor idea catalogarlo por lo que es. El problema de ver al viejo canal Spice—no recuerdo si llevaba o no un logo—en aquel viejo televisor Zenith, Modelo CP1920, no era el simple saber que para poder verlo tendría que resignarme a también tener que verle la calva a mi tío mientras se paraba frente al televisor, pues, masturbándose, sino que yo no podía subir el maldito volumen. El egoísta de Vásquez utilizaba los audífonos, una de las múltiples utilidades de este modelo de televisor, y yo, asechando por las brechas de la persiana, debajo de mi colcha, no tenía ni la menor idea de qué tan bien estaban follando a la dama.` },
      { index: 12, text: `El viejo búho y el mochuelo se hacían de sus alas y vista para así terminar el silencioso vuelo. Pero aquello—el ingenuo círculo vicioso entre Vásquez, Srta. Zenith y yo—ocurría dos horas antes de despertar y volver a la faena; antes de ducharme en agua caliente, razón por la cual mi piel oscura blanqueó. No me gustaba estar parado ahí, en el baño, mirando las losetas azulejas, analizando el goteo de la ducha o contando las arrugas cutáneas formándoseme sobre la punta de mis flacos dedos. Salía en cuanto lavase mis calzoncillos y calcetines. Disponía de mi propio jabón, toalla y cepillo dental, me los entregó Vásquez el primer día bajo su régimen envueltos dentro de una sábana blanca, de esas que llevan elástico y que siempre adherimos a las cuatro esquinas del colchón austeramente. Mi cama era talla Twin, aunque su gemela nunca le vi pasar, la de madre King, igual que la de Vásquez, dormían juntos. Recuerdo que después de entregarnos nuestras respectivas necesidades, Vásquez tomó un muletazo hacia abajo, a mi sorpresa; no tenía la menor idea de que nuestra nueva casa estaba debajo.` },
      { index: 13, text: `Era una piedra moldeada en forma de cueva, en forma del blando y falso caparazón de una cochinilla. Doce, los escalones de la negra escalera, aquella en la que ahora pienso tras oír lo de tío. Sé porque contaba cada paso de la comadreja, a lo mejor ahora lo hace con una de las llantas. Ya no nos hablamos y me cuesta preguntarle cómo le ha ido con su nueva pierna, si le habría puesto un nombre ya, que si tal vez pensará en mudarse a otro sitio ahora que trae con él un par de ruedas ajustadas a una silla. Le mandé mis recuerdos con madre, ella fue a visitarlo ayer, pedí exclamación en que ¡lo extraño mucho! Mentía, pero debía cumplir con mis responsabilidades como familiar de él que soy, diría. ¿De qué estaba hablando? ¡Sí, cierto! De la primera vez que pisé la escalera negra de piedra maciza, de la primera vez que nos frenó de plano frente al portón de hierro oxidado y, mirándonos fuertemente a los ojos con el labio superior inclinado, el tío Vásquez nos dijo, en una voz muy elocuente y suasoria—aquí… mando yo.` },
      { index: 14, text: `Me llamó a la puerta y, entregándome una llave cubierta de plástico verde, me señaló que abriera la cerradura. Al darle una vuelta al pomo, salió un sonido oxidado y sonoro, como si un mecanismo continuo ejerciera el mismo movimiento una vez cada centenario, como cuando incrustas la cabeza del hacha en un tronco lleno de nudos. Es increíble tener la capacidad de recordar el sonido exacto que solía hacer algún objeto o de poder revivir momentos por medio de las palabras dichas, las que tanto te impactaron. Más increíble aun, pensar que las personas que ahora escuchas puedan estar mudas y que solamente escuchas palabras que dispones en tu memoria.` },
      { index: 15, text: `Ya entrando por el portón, a mi almacén de sonidos añadí el silbido de las tuberías de la calefacción que corrían a lo largo del pasillo principal. Sonido comparable con la tetera ardiente, el estallar de la cuaba en el anafre o el suave soplo de tu abuela sobre su taza de café. Por estos mismos tubos, valiéndome de mi sentido de olfato, también corrían ladrillos de mierda privada de fibra. Vásquez nos advirtió que tuviéramos cuidado no tocar los abre-pasos de las tuberías y que, por más que pensáramos que había una evidente fuga de gas, no nos alertáramos, que solamente era el inquilino de la primera pensión—la primera puerta, la puerta A—a la derecha. En total, el sótano disponía de cuatro habitaciones, en las cuales tres estaban alquiladas, sin incluir el pago semanal de madre. El cobayo Vásquez había capitalizado en un sótano que una vez representó el cuarto de maquinaria para calefacción y el armario de herramientas.` },
      { index: 16, text: `El inquilino de la pensión A se llamaba Jorge y se auto apodaba El Bori, de acuerdo con lo que nos decía tío al caminar por el pasillo. Ni a dos muletazos de la primera puerta, se paró y deslizando sus anteojos hacia abajo con una de sus uñas martilladas, nos dijo Vásquez—esta vez en voz baja, comprometedora a un acercamiento, a un rose de labios a oídos, de nariz con aliento, de saliva a nariz—ese es un periquero. In principio, idea de lo que fuese un ‘periquero' no la tenía, pero después de ver la acción que hizo con su dedo índice contra su nariz pude hacerme de varias conclusiones. Continuábamos el tour du sous-sol con detalles finales acerca de dónde poner las sombrillas en caso de lluvia y las botas en caso de nieve y qué hacer con el extinguidor y la cubeta de arena en caso de fuego.` },
      { index: 17, text: `Finalmente, llegamos al primer espacio en donde se podía notar el cambio de maquinaria a hogar. Noté que el piso de cemento cuarteado pasó a losetas niveladas y dispersas, que la oscuridad desapareció bajo docenas de luces proyectadas por lámparas y velones ilustrados con San Miguel, que las tuberías cruzadas por las paredes fueron reemplazadas por fotos de difuntos y que el olor a mierda cambió a café. Ya en la cocina, Vásquez nos dio una pequeña advertencia sobre el uso de la comida ajena; insistió que cada persona debe comer lo suyo y solamente lo suyo, no importe quien sea. La cocina—fijándome en los ángulos del techo, las diferentes entradas y salidas—formaba parte del segundo pasillo, estaba estructurada en forma de ‘u' y, más importante aún, daba paso al patio—el basurero del edificio—después de cruzar hasta el fondo del pasillo justo detrás del refrigerador.` },
      { index: 18, text: `Frente a la estufa se encontraba la única ventana dentro del laberinto; debajo, madre y Vásquez sembraban plantas, ajíes y hierbas—en la tierra vivía la lombriz. Durante el invierno yo salía a remover la nieve que se acumulaba sobre el cristal y las garras de hielo que se formaban debido al goteo de las tuberías. Me gustaba salir al patio en las mañanas de febrero cuando la nieve blanca, virgen apenas terminaba de caer. El contraste entre lo blanco y lo oscuro aumentaba exponencialmente justo antes de salir el sol. En medio del patio crecía un arce gigantesco de ramas largas y fuertes, de tronco erecto y frondoso, habitado por un búho chico semejante a un gato. Se parecía mucho a Vásquez en su forma de ser, su manera de observar a todos los demás silenciosamente desde su trono. Por las mañanas, también arrullaban las palomas equilibradas sobre el cable eléctrico, abriendo y cerrando los ojos como esas viejas muñecas que con cualquier movimiento a la cabeza abrían y cerraban sus ojos de cristal.` },
      { index: 19, text: `Al estar localizado entre dos edificios, el viento de febrero no soplaba tan fuerte en el patio que como en la avenida Fulton, creando así un paraíso para los animales salvajes y realengos que aún habitaban estas sucias áreas. Aves pequeñas habitaban los huecos entre los ladrillos caídos ojeando granos de arroz, las ratas se sumergían entre los zafacones hartándose de todo lo que le cupiera entre el hocico, las ardillas de un árbol muerto corrían por doquier en busca de panecillos que tiran en las aceras, y los perros realengos—los cuales yo llamaría viralatas—mordían entre bolsas de basura que los inquilinos tiraban por las ventanas, en busca de un par de huesos chupados. Aquello de la basura, los perros y las ventanas molestaba mucho a mi tío Vásquez; se pasaba horas buscando entre bolsas plásticas alguna prueba de cuál inquilino estaba arrojando basura de las ventanas. Tenía una idea de quién podía ser—el del piso tres (C), Pedro Alfonso Jiménez Amado—pero nunca pudo comprobar sus dudas. Fue tanto su afán de comprobar que Pedro arrojaba bolsas de basura por la ventana que se pasó, con mi ayuda, una semana enumerando todas las ventanas de los edificios con el número del apartamento correspondiente debajo de ellas y, una semana después, empleó la segunda faceta de su plan: pasarse un fin de semana completo en el edificio de al lado, en un apartamento justamente paralelo, vigilando los movimientos del inquilino Pedro, apartamento 3C.` },
      { index: 20, text: `Vásquez decidió utilizar el apartamento de una familia—los nombres, por ahora, no importan—que estaba de vacaciones invernales en Puerto Plata. La familia también había planificado fumigar el apartamento durante su estadía fuera del país, dándole a Vásquez todo control sobre sus planes. Como perro fiel, no hice preguntas, sólo seguí sus pasos hasta llegar al apartamento 3M, del edificio adyacente. Al llegar, me di cuenta de que el apartamento no estaba vacío, que en vez de prepararme para "fumigar", en verdad, me había preparado para acampar en el hogar de alguien a quien aún no conocía. Antes de cerrar la puerta, tío cubrió el marco de la puerta con una sábana plástica que advertía "NO ENTRAR. FUMIGACIÓN EN PROCESO." Pasándome un bulto, me señaló al refrigerador con su labio superior, como de costumbre. Al abrirlo, igual que cuando abrimos el apartamento 3M, me sorprendió no ver comida dentro, solamente las gavetas y los cristales limpios reflejando la luz del pequeño bombillo que prendía con el abrir de la puerta.` },
      { index: 21, text: `Buen refrigerador, marca Maytag. ¿Por qué lo dejaron prendido? pregunté aquel día sin alcanzar una respuesta. Con su dedo índice me pidió silencio. En el bulto: café, pan, queso, jamón, y leche, junto con utensilios, una toalla y dos cepillos dentales. Justo cuando comencé a organizar la comida, Vásquez se paró frente a mí y con sus dedos de barilla gruesa me señaló la ración de leche, pan, queso y jamón que me tocaba. En total: cuatro lonjas de pan, una lonja de jamón (dos de queso) y una taza y media de leche, para todo el fin de semana. La primera noche no comí, pues ya había merendado en la escuela, era viernes, y también cené en la casa antes de salir con tío. En menos de una hora ya teníamos la puerta herméticamente sellada, la comida organizada y dividida racionalmente y la cama arreglada para los dos. Vásquez decidió mover la mesa en medio de la sala hacia un lado y de tirar las sábanas sobre esta área del apartamento.` },
      { index: 22, text: `Aunque no tenía la colcha, puedo decir que, con el abrigo y mis botas aún puestas, duré gran parte de la noche cómodo y tostadito, pero en la madrugada—entre las 02:00 y 03:00—tío, al igual que yo, no lográbamos dormir. Llegamos a un muy rápido acuerdo de que debíamos dormir sobre una cama y no el piso frío, él se fue a la grande y yo a la más chica; los apartamentos tenían el mismo modelo y navegar en la oscuridad no se nos resultaba difícil. No sé la de Vásquez, pero mi nueva cama—talla Queen—estaba llena de cojines, almohadillas y objetos que se sentían suaves, con extremidades parecidas a la de un osito peluche, en mis manos. No le hice mucho caso a los peluches y comencé a removerle la funda a uno de los varios cojines; si iba a lograr dormir tendría que mantener mis rutinas al tanto.` },
      { index: 23, text: `A los diez minutos caí como una guanábana, roncando como nunca, sobre aquella suave cama de almohadas fragantes. Ni bien cerré los ojos, sentí un temblor a lo largo de mis piernas y la cama—Vásquez despertándome. Eran las 05:00, un sábado cualquiera, a finales de febrero, 2002. Decidí desayunar media lonja de pan con la misma cantidad de queso, humectando el pan con un buche de leche fría. Tío Vásquez casi mente comió lo mismo, si recuerdo bien, lo único que cambió fue su cantidad de pan; siempre decía que en su estómago el pan se convertía en azúcar y trataba de no consumirlo. Fiándose de que si mantenía un buen reglamento en su dieta podía continuar tomando whiskey todos los fines de semana. Me doy cuenta ahora, después de vivir cuatro años junto a él, que ese sábado fue la primera vez que no sentí el fuerte olor a alcohol sobre su barba. Allí, despertando en el apartamento ajeno, descubrí que había dormido en el cuarto de una muchacha—supe por el color purpura en las paredes, los ositos peluches abrazándome el cuello, los retratos de una muchacha luciendo un vestido detallado en piedras preciosas, tal vez su quinceañero, y el letrero de ‘Princesa' que posaba sobre el marco de la puerta.` },
      { index: 24, text: `Estaba desnudo bajo la colcha de flores que voluntariamente elegí, mis pies cautelosamente mostrando las uñas, flexionando suavemente. En vez de enfocarme mucho en mi alrededor, las fotos de su presunto quinceañero, el olor a flores sobre las sábanas y almohadas, opté por buscar los jeans que guindé en el pomo de la puerta, la camisa que logró alcanzar un cuadro de globos cerca a la ventana, los calzoncillos que lancé hacia la alfombra con los dedos más gordos de mis pies, y la vieja funda multiusos—convertida en babosa—que guardé debajo del colchón rosado. Mis calcetines y botas estaban tostándose sobre la calefacción del baño desde antes de entrar a la colorida habitación, la nieve y sal de las suelas había desaparecido. Solamente me puedo imaginar lo que hizo tío al otro lado del campamento.` },
      { index: 25, text: `Sin duda alguna, sé que durmió en el suelo sobre la sábana que él mismo trajo del sótano, que no se quitó la ropa, siquiera las botas, que aquella toalla que, en el bulto, anoche dejé ha de estar dobladita y pegajosa bajo su sábana, en forma de cabecera. Que la ración de leche que le tocaba por el resto del fin de semana, se la ha bebido anoche por la debilidad de su hígado. También sé que las luces de la avenida no lo dejaron dormir, que le hacían falta los gases que de las tuberías salían, que estaba calculando cuantas hojuelitas sobraban en su embace de cereal Kellogg's, y que—a espaldas de mí—el sonido que salía de su habitación no era un programa de animales en la selva, como el quiso darme a creer después de escuchar al elefante introduciendo su trompa.` },
      { index: 26, text: `—Vete a dormir —me dijo—, estoy viendo al Discovery Channel.` },
      { index: 27, text: `Me gustaba mucho ese canal, muy informativo; referencia para mis maestros de ciencias, especialmente cuando no sabían qué enseñar. A mediados de la primera década del siglo veintiuno, tiempo muy justo, estrenaron un programa semanal llamado ‘Tierra' que recorría el mundo en busca de las distintas capacidades y impresionantes acciones del reino animal. El océano pacífico, las amazonas, los llanos africanos, los picos suizos, isla de pascua, el polo blanco y el negro, entre los más interesantes lugares presentados. Pero Tierra era los jueves a las 20:00, hora exacta en que madre comenzaba a ver sus novelas en Univisión y Telemundo—cambiaba canales entre anuncios—de lunes a viernes. Valiéndome de mis oídos y las grietas en la persiana, la salvadoreña de la pensión B y la mexicana de la C salían de sus cuevas a ver novelas. Tío las acompañaba buscando compañía, manteniéndose al margen de la comunidad que compuso, atorado en su mueble con la comadreja reclinada, haciendo preguntas que capítulos anteriores habían respondido.` },
      { index: 28, text: `Se pasaban tres horas cacareando y colando café Bustelo, intrigados por saber quién fue que mató al padre y dónde se encontraba la, supuesta, hija secuestrada. Aunque podía escucharlos, una noche común y corriente, en mi habitación, comencé a cerrar los ojos mientras aún estaba despierto. Lo primero que vi fueron cuatro paredes y los rostros de aquellos que, alrededor de la Zenith CP1920, discutían teorías y descartaban conclusiones con faltas de base.` },
      { index: 29, text: `—Creo que a él lo mató su esposa tras encontrarlo en la playa con otra mujer —dijo la salvadoreña de la pensión B.` },
      { index: 30, text: `—En el caso de que sí fuese su esposa que lo haya matado, y créeme que gran parte de mí está de acuerdo con tu teoría, especialmente sabiendo que Carlos —el esposo, el malo, el antagonista—le ha pegado los cuernos varias veces a Beatriz —la esposa, la buena, la protagonista—nos quedaría la duda de la hija… Si fue su esposa quien lo mató, ¿dónde está la hija? —le respondía madre a la salvadoreña.` },
      { index: 31, text: `—¿A lo mejor también murió? —añadió la mexicana de la pensión C.` },
      { index: 32, text: `—Entonces, ¿quién la mató? —preguntó madre.` },
      { index: 33, text: `La novela apenas comenzaba a transmitirse; una nueva historia con que entretener sus cortas noches. No estaba mal discutir teorías sobre novelas, de todos modos, era lo mismo que hacíamos por la mañana en la clase de literatura con míster Jackson. El problema de las tantas discusiones eran los constantes ruidos: las carcajadas, los gritos repentinos y el golpe del reclinatorio al mecerse contra la persiana. No podía concentrarme en mis tareas de lectura y, aquella noche a eso de las 20:30, puse mi libro—Of Mice and Men, de John Steinbeck—bajo mi almohada para nunca más volverlo a abrir. Cerré los ojos fuertemente hasta blanquear, hasta sólo ver los hinchados vasos sanguíneos de las retinas dentro de mis parpados, hasta sentir el dolor en medio de mi cabeza al parar de respirar.` },
    ],
  },

  "capitulo-dos": {
    slug: "capitulo-dos",
    bookSlug: "recoleta",
    number: 2,
    romanNumeral: "DOS",
    title: "Capítulo Dos",
    subtitle: "La escuela, la nieve, el despertar",
    epigraph: {
      text: "El sueño comenzaba de la misma manera.",
      attribution: "Recoleta",
    },
    isLocked: true,
    wordCount: 4542,
    paragraphs: [
      // SEALED — unlocks when you subscribe
    ],
  },

  "capitulo-tres": {
    slug: "capitulo-tres",
    bookSlug: "recoleta",
    number: 3,
    romanNumeral: "TRES",
    title: "Capítulo Tres",
    subtitle: "Los pasillos, los monitores, el ruido",
    epigraph: {
      text: "Cada cambio de hora resultaba en un cambio de salón.",
      attribution: "Recoleta",
    },
    isLocked: true,
    wordCount: 2597,
    paragraphs: [
      // SEALED — unlocks when you subscribe
    ],
  },

  "capitulo-cuatro": {
    slug: "capitulo-cuatro",
    bookSlug: "recoleta",
    number: 4,
    romanNumeral: "CUATRO",
    title: "Capítulo Cuatro",
    subtitle: "Las palabras olvidadas",
    epigraph: {
      text: "Siroco. Gorguera. Gorjal.",
      attribution: "Recoleta",
    },
    isLocked: true,
    wordCount: 80,
    paragraphs: [
      // SEALED — unlocks when you subscribe
    ],
  },
};

export function getRecoletaChapter(slug: string): Chapter | null {
  return RECOLETA_CHAPTERS[slug] ?? null;
}

export function getAllRecoletaChapterSlugs(): string[] {
  return Object.keys(RECOLETA_CHAPTERS);
}
